### ISSUE TITLE
Act_user_manager_no_service - Symbol not found

### ISSUE THREAD

**Issue by rba-andrade** [jovanlanik/gtklock-userinfo-module#1]
Hi,

I'm getting the following error whiole running "gtklock -li" with the userinfo-module installed.

** (gtklock:16180): WARNING **: 18:11:41.949: Module loading failed: Error relocating /usr/local/lib/gtklock/userinfo-module.so: act_user_manager_no_service: symbol not found

I compiled it using a musl distro (Alpine Linux)

**Comment by jovanlanik** [comment]
This is an issue caused by the compile flags when compiling the module. What kind of tools are you using? Do you use any special flags? One flag known to cause this is `-Wl,--as-needed`. Try building with `-Wl,--no-as-needed`.

**Comment by rba-andrade** [comment]
It did work with -Wl,--no-as-needed. Thanks.
