### ISSUE TITLE
Request point release

### ISSUE THREAD

**Issue by BluishHumility** [jovanlanik/gtklock-userinfo-module#10]
Hello,

I have tested and confirmed this commit has resolved the issue with gtklock segfaulting when using the userinfo module: https://github.com/jovanlanik/gtklock-userinfo-module/commit/aa4b5832185d2dd9e7f88826fd9d03e3d5ea1ad6

Is it possible to publish a point release, so the repo package can benefit from this fix?

Thank you! :wave:

**Comment by jovanlanik** [comment]
Done, thanks for bringing it to my attention.
