### ISSUE TITLE
userinfo-module: User name not found

### ISSUE THREAD

**Issue by DuplicantWood** [jovanlanik/gtklock-userinfo-module#3]
Hi i am seeing this whenever i run gtklock with this module enabled

```
** (gtklock:95610): WARNING **: 01:02:52.554: userinfo-module: User name not found

** (gtklock:95610): WARNING **: 01:02:52.554: userinfo-module: User image not found
segmentation fault (core dumped) 
```
dmesg

``gtklock[101519]: segfault at 557ae116be16 ip 00007f5d2582d1f1 sp 00007ffdb1c32858 error 4 in libgobject-2.0.so.0.7600.2[7f5d25803000+34000] ``

I still see both my user name and image displayed correctly on the gtklock screen with this error.

Thanks

**Comment by jovanlanik** [comment]
Should be fixed in the latest master.
