### ISSUE TITLE
userinfo-module below the clock

### ISSUE THREAD

**Issue by RoccoRakete** [jovanlanik/gtklock-userinfo-module#4]
Is it possible to position the userinfo below the clock? If yes, how?

**Comment by RoccoRakete** [comment]
Ahh I've just found it!
For anyone searching for the same option it's the line `{ "under-clock", 0, 0, G_OPTION_ARG_NONE, &under_clock, NULL, NULL },`

configured trough `under-clock=true`

**Comment by jovanlanik** [comment]
Seems you found what you needed 🙂
Closing issue...
