### ISSUE TITLE
Document user settings

### ISSUE THREAD

**Issue by werdahias** [jovanlanik/gtklock-userinfo-module#5]
It'd be nice if the options added for userinfo-module were document somewhere. I looked at the source code and gathered that the user image can be set via` user_image = path/to/image` in `gtklock/config.ini` but it might not be that easy for other users. 
I'll be glad to provide a MR to add documentation for `user_name` and `user_image`

**Comment by jovanlanik** [comment]
Hi, the user image and user name can't be set in the config file.
Learn how to set them here: https://github.com/jovanlanik/gtklock-userinfo-module/wiki
You can also check all available config options by running `gtklock --help-all`

**Comment by werdahias** [comment]
thanks, I must've missed that.
