### ISSUE TITLE
get a black screen when use the userinfo-module

### ISSUE THREAD

**Issue by ffs-akl** [jovanlanik/gtklock-userinfo-module#8]
if started the gtklock without userinfo-module, everthing is ok.  but always got a black screen with userinfo-module after login 

OS: arch linux in vmware
DE: lxqt+labwc(wayland only)

**Comment by jovanlanik** [comment]
duplicate issue #7

**Comment by jovanlanik** [comment]
Can you try the latest userinfo module commit (aa4b5832185d2dd9e7f88826fd9d03e3d5ea1ad6) ?

**Comment by ffs-akl** [comment]
thank you,  it work now.
