### ISSUE TITLE
How to enable  horizontal-layout of userinfo  in  config.ini

### ISSUE THREAD

**Issue by ffs-akl** [jovanlanik/gtklock-userinfo-module#9]
I can use the comman` gtklock --horizontal-layout ` to make it effective. but how to enable `--horizontal-layout `of userinfo  in  config.ini?
Please take a look at this issue.

**Comment by jovanlanik** [comment]
Add this section to your config file:
```
[userinfo]
horizontal-layout=true
```

**Comment by ffs-akl** [comment]
Thank you,  It worked.
